function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "calcMBD_subsys"};
	this.sidHashMap["calcMBD_subsys"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "calcMBD_subsys:11"};
	this.sidHashMap["calcMBD_subsys:11"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<Root>/In1"] = {sid: "calcMBD_subsys:1"};
	this.sidHashMap["calcMBD_subsys:1"] = {rtwname: "<Root>/In1"};
	this.rtwnameHashMap["<Root>/In2"] = {sid: "calcMBD_subsys:2"};
	this.sidHashMap["calcMBD_subsys:2"] = {rtwname: "<Root>/In2"};
	this.rtwnameHashMap["<Root>/basicCalc"] = {sid: "calcMBD_subsys:11"};
	this.sidHashMap["calcMBD_subsys:11"] = {rtwname: "<Root>/basicCalc"};
	this.rtwnameHashMap["<Root>/Out1"] = {sid: "calcMBD_subsys:7"};
	this.sidHashMap["calcMBD_subsys:7"] = {rtwname: "<Root>/Out1"};
	this.rtwnameHashMap["<Root>/Out2"] = {sid: "calcMBD_subsys:8"};
	this.sidHashMap["calcMBD_subsys:8"] = {rtwname: "<Root>/Out2"};
	this.rtwnameHashMap["<Root>/Out3"] = {sid: "calcMBD_subsys:9"};
	this.sidHashMap["calcMBD_subsys:9"] = {rtwname: "<Root>/Out3"};
	this.rtwnameHashMap["<Root>/Out4"] = {sid: "calcMBD_subsys:10"};
	this.sidHashMap["calcMBD_subsys:10"] = {rtwname: "<Root>/Out4"};
	this.rtwnameHashMap["<S1>/In1"] = {sid: "calcMBD_subsys:12"};
	this.sidHashMap["calcMBD_subsys:12"] = {rtwname: "<S1>/In1"};
	this.rtwnameHashMap["<S1>/In2"] = {sid: "calcMBD_subsys:13"};
	this.sidHashMap["calcMBD_subsys:13"] = {rtwname: "<S1>/In2"};
	this.rtwnameHashMap["<S1>/Add"] = {sid: "calcMBD_subsys:3"};
	this.sidHashMap["calcMBD_subsys:3"] = {rtwname: "<S1>/Add"};
	this.rtwnameHashMap["<S1>/Divide"] = {sid: "calcMBD_subsys:5"};
	this.sidHashMap["calcMBD_subsys:5"] = {rtwname: "<S1>/Divide"};
	this.rtwnameHashMap["<S1>/Product"] = {sid: "calcMBD_subsys:6"};
	this.sidHashMap["calcMBD_subsys:6"] = {rtwname: "<S1>/Product"};
	this.rtwnameHashMap["<S1>/Subtract"] = {sid: "calcMBD_subsys:4"};
	this.sidHashMap["calcMBD_subsys:4"] = {rtwname: "<S1>/Subtract"};
	this.rtwnameHashMap["<S1>/Out1"] = {sid: "calcMBD_subsys:14"};
	this.sidHashMap["calcMBD_subsys:14"] = {rtwname: "<S1>/Out1"};
	this.rtwnameHashMap["<S1>/Out2"] = {sid: "calcMBD_subsys:15"};
	this.sidHashMap["calcMBD_subsys:15"] = {rtwname: "<S1>/Out2"};
	this.rtwnameHashMap["<S1>/Out3"] = {sid: "calcMBD_subsys:16"};
	this.sidHashMap["calcMBD_subsys:16"] = {rtwname: "<S1>/Out3"};
	this.rtwnameHashMap["<S1>/Out4"] = {sid: "calcMBD_subsys:17"};
	this.sidHashMap["calcMBD_subsys:17"] = {rtwname: "<S1>/Out4"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
