function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "trafficLight_SF"};
	this.sidHashMap["trafficLight_SF"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "trafficLight_SF:1"};
	this.sidHashMap["trafficLight_SF:1"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<Root>/Chart"] = {sid: "trafficLight_SF:1"};
	this.sidHashMap["trafficLight_SF:1"] = {rtwname: "<Root>/Chart"};
	this.rtwnameHashMap["<Root>/Lamp"] = {sid: "trafficLight_SF:8"};
	this.sidHashMap["trafficLight_SF:8"] = {rtwname: "<Root>/Lamp"};
	this.rtwnameHashMap["<Root>/Lamp1"] = {sid: "trafficLight_SF:9"};
	this.sidHashMap["trafficLight_SF:9"] = {rtwname: "<Root>/Lamp1"};
	this.rtwnameHashMap["<Root>/Lamp2"] = {sid: "trafficLight_SF:10"};
	this.sidHashMap["trafficLight_SF:10"] = {rtwname: "<Root>/Lamp2"};
	this.rtwnameHashMap["<Root>/Out1"] = {sid: "trafficLight_SF:2"};
	this.sidHashMap["trafficLight_SF:2"] = {rtwname: "<Root>/Out1"};
	this.rtwnameHashMap["<Root>/Out2"] = {sid: "trafficLight_SF:3"};
	this.sidHashMap["trafficLight_SF:3"] = {rtwname: "<Root>/Out2"};
	this.rtwnameHashMap["<Root>/Out3"] = {sid: "trafficLight_SF:4"};
	this.sidHashMap["trafficLight_SF:4"] = {rtwname: "<Root>/Out3"};
	this.rtwnameHashMap["<S1>:4"] = {sid: "trafficLight_SF:1:4"};
	this.sidHashMap["trafficLight_SF:1:4"] = {rtwname: "<S1>:4"};
	this.rtwnameHashMap["<S1>:1"] = {sid: "trafficLight_SF:1:1"};
	this.sidHashMap["trafficLight_SF:1:1"] = {rtwname: "<S1>:1"};
	this.rtwnameHashMap["<S1>:3"] = {sid: "trafficLight_SF:1:3"};
	this.sidHashMap["trafficLight_SF:1:3"] = {rtwname: "<S1>:3"};
	this.rtwnameHashMap["<S1>:2"] = {sid: "trafficLight_SF:1:2"};
	this.sidHashMap["trafficLight_SF:1:2"] = {rtwname: "<S1>:2"};
	this.rtwnameHashMap["<S1>:5"] = {sid: "trafficLight_SF:1:5"};
	this.sidHashMap["trafficLight_SF:1:5"] = {rtwname: "<S1>:5"};
	this.rtwnameHashMap["<S1>:6"] = {sid: "trafficLight_SF:1:6"};
	this.sidHashMap["trafficLight_SF:1:6"] = {rtwname: "<S1>:6"};
	this.rtwnameHashMap["<S1>:7"] = {sid: "trafficLight_SF:1:7"};
	this.sidHashMap["trafficLight_SF:1:7"] = {rtwname: "<S1>:7"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
